apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebar-v2-preparing
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-pull
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebar-v2-solving
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-pull
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebar-v2-fitting
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-pull
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebar-v2-baring
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-pull
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebar-v2-validation
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-pull
