from __future__ import annotations

import os

REBAR_MAX_JOBS_PER_TASK = int(os.getenv("REBAR_MAX_JOBS_PER_TASK", "28031998"))
REBAR_GLOBAL_MAX_JOBS = int(os.getenv("REBAR_GLOBAL_MAX_JOBS", "28031998"))
REBAR_SCHEDULER_BATCH_SIZE = int(os.getenv("REBAR_SCHEDULER_BATCH_SIZE", "256"))
REBAR_COMBINE_BATCH_SIZE = int(os.getenv("REBAR_COMBINE_BATCH_SIZE", "256"))
REBAR_DEFAULT_SOLVER_THREADS = int(os.getenv("REBAR_DEFAULT_SOLVER_THREADS", "1"))
REBAR_MAX_SOLVER_THREADS = int(os.getenv("REBAR_MAX_SOLVER_THREADS", "4"))
REBAR_COMPONENT_READY_QUEUE = os.getenv("REBAR_COMPONENT_READY_QUEUE", "rebar:component:ready")
REBAR_COMPONENT_PROCESSING_QUEUE = os.getenv("REBAR_COMPONENT_PROCESSING_QUEUE", "rebar:component:processing")
REBAR_COMPONENT_WORKLOAD_QUEUE = os.getenv("REBAR_COMPONENT_WORKLOAD_QUEUE", "rebar:component:workload")
