apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rebar-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
spec:
  ingressClassName: nginx
  rules:
    - host: rebar.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rebar-api
                port: {number: 80}
