apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rebar-optimizer
resources:
- ../../base
- keda-auth.yaml
- worker-scaledobject.yaml
- ingress.yaml
images:
- name: ghcr.io/contextmachine/a101_reinforcement_am
  newName: ghcr.io/contextmachine/a101_reinforcement_am
  newTag: am-super-branch
