apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rebar-worker
spec:
  scaleTargetRef:
    name: rebar-worker
  pollingInterval: 5
  cooldownPeriod: 300
  minReplicaCount: 0
  maxReplicaCount: 28031998
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
  triggers:
  - type: redis
    metadata:
      address: rebar-redis.rebar-optimizer.svc.cluster.local:6379
      listName: rebar:jobs:workload
      listLength: '1'
      activationListLength: '0'
    authenticationRef:
      name: rebar-redis-auth
